name = "de-graphql"
main = "src/index.ts"
compatibility_date = "2024-06-01"

[vars]
# 开发环境环境变量
DEEPSEEK_API_URL = "https://api.deepseek.com/v1"
DEEPSEEK_API_KEY = "sk-acd1d3699e9d433e8d96d9d74c5a73de"

# 注意：生产环境中应该在 Cloudflare Dashboard 中设置为 Secrets